### ISSUE TITLE
Move to JuliaArrays

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/LabelledArrays.jl#1]
@timholy ?

**Comment by timholy** [comment]
Sounds good to me. A few code comments:
- README should link to `StaticArrays` and make it clear that objects/concepts like `FieldVector` and `MArray` come from there
- README should clarify why an `LMArray` is not fully mutable (they are based on `MArray` which is mutable)
- if it's going to be at JuliaArrays, it shouldn't depend on `Juno` (needs to be agnostic with respect to environment). You might need to create a "glue module" (see https://github.com/JuliaLang/julia/issues/2025#issuecomment-338005473) that lives outside JuliaArrays.
- docstring for `@SLVector` mentions a `Type` input but that seems to have been removed (or never added).
- README shows `@LMArray` and `@LArray` but the code seems to be `@LMVector` and `@LVector`.

**Comment by MikeInnes** [comment]
A dependency on Juno.jl doesn't stop this from being agnostic to environment. It is itself a glue module.

**Comment by ChrisRackauckas** [comment]
Yeah, the README and docstrings are a little off because I am still hacking away at a few things. I'll get that all cleaned up soon. This is all still WIP.

As for Juno.jl, I had it to try and fix the display. I can do that in a Requires block though, but didn't want to fiddle with that quite yet.

**Comment by timholy** [comment]
If Juno is just a glue module (didn't properly realize that, though I see it's effectively stated in the README), then I'm fine with leaving it in. Hopefully folks don't check `isdefined(Main, :Juno)` to make guesses about which environment the user is running.
