### ISSUE TITLE
Strange behavior when numerically converting an `@SLVector`

### ISSUE THREAD

**Issue by MSeeker1340** [JuliaDiffEq/LabelledArrays.jl#15]
```julia
julia> @SLVector ABC Int [a,b,c]

julia> x = ABC(1,2,3)
3-element ABC:
 1
 2
 3

julia> Float64.(x)
3-element ABC:
 1
 2
 3

julia> convert.(Float64, x)
3-element ABC:
 1
 2
 3
```

This is causing AD to fail in OrdinaryDiffEq when the initial data is given as an `@SLVector`. Related issue: https://github.com/JuliaDiffEq/LabelledArrays.jl/issues/14

**Comment by ChrisRackauckas** [comment]
We really just need to redo SLVector to be more like LVector. I might do that on the flight tonight
