### ISSUE TITLE
Make LMArray labels fast

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/LabelledArrays.jl#2]
I was hoping

```julia
Base.@pure function symbol_to_index(names::SArray, s::Symbol)
    findfirst((t)->s==t,names)
end
```

or

```julia
Base.@pure function symbol_to_index(names, s::Symbol)
    i = 0
    for n in names
        i += 1
        n == s && return i
    end
    return error("Label not valid")
end
```

would make

```julia
@inline function Base.getindex(A::LMArray{S,T,N,L}, s::Symbol) where {L,N,T,S<:Tuple}
    A.values[symbol_to_index(A.names, s)]
end
```

the `symbol_to_index` call be essentially free after the first time it compiles and basically makes a map between symbols and indices, but that doesn't seem to be the case. Do I need to `Val{s}`? That would be fine, especially after https://github.com/JuliaLang/julia/issues/1974 . 

@mbauman @timholy can I call on your expertise for some advice here on pure functions? There must be some way to get Julia to know that the names are constant in some form and optimize on that for literals.

**Comment by ChrisRackauckas** [comment]
Looks like https://github.com/JuliaLang/julia/issues/24441 will fix this. 

Refs: 

https://github.com/JuliaLang/julia/issues/24011
https://github.com/JuliaLang/julia/issues/24441

**Comment by mbauman** [comment]
Did you figure this one out?  I don't think a `@pure` function is allowed to throw errors, since you're telling the compiler it's safe to execute at _any_ time, including in inference and compilation.

**Comment by ChrisRackauckas** [comment]
I'm going to wait until v0.7 to see if any of the inference changes help. I think the correct interface for this is via getfield overloading, in which case that should be fast I think if it optimizes on the constant correctly. That or IPO should do the trick.
