### ISSUE TITLE
Broadcast error for `LArray`s of different types

### ISSUE THREAD

**Issue by MSeeker1340** [JuliaDiffEq/LabelledArrays.jl#25]
On master:

```julia
julia> using LabelledArrays

julia> x = @LArray [1, 2] (:a, :b)
2-element LArray{Int64,1,(:a, :b)}:
 1
 2

julia> y = Float64.(x)
2-element LArray{Float64,1,(:a, :b)}:
 1.0
 2.0

julia> x .+ y
ERROR: conflicting broadcast rules defined
  Broadcast.BroadcastStyle(::LabelledArrays.LAStyle{Float64,1,(:a, :b)}, ::LabelledArrays.LAStyle{Int64,1,(:a, :b)}) = LabelledArrays.LAStyle{Float64,1,(:a, :b)}()
  Broadcast.BroadcastStyle(::LabelledArrays.LAStyle{Int64,1,(:a, :b)}, ::LabelledArrays.LAStyle{Float64,1,(:a, :b)}) = LabelledArrays.LAStyle{Int64,1,(:a, :b)}()
One of these should be undefined (and thus return Broadcast.Unknown).
```

`SVector` is fine:

```julia
julia> AB = @SLVector (:a,:b)
SLArray{Tuple{2},1,(:a, :b),T} where T

julia> x = AB(1,2)
2-element SLArray{Tuple{2},1,(:a, :b),Int64}:
 1
 2

julia> y = Float64.(x)
2-element SLArray{Tuple{2},1,(:a, :b),Float64}:
 1.0
 2.0

julia> x .+ y
2-element SLArray{Tuple{2},1,(:a, :b),Float64}:
 2.0
 4.0
```

**Comment by MSeeker1340** [comment]
Could this be what is missing?

https://docs.julialang.org/en/v1/manual/interfaces/#writing-binary-broadcasting-rules-1

Also, @YingboMa why are we implementing a custom style instead of the recommended `Broadcast.ArrayStyle`? (https://docs.julialang.org/en/v1/manual/interfaces/#Broadcast-Styles-1)

**Comment by ChrisRackauckas** [comment]
Yes, it should be a `Broadcast.ArrayStyle`. I think there are insurmountable bugs if you don't use it right now.

**Comment by YingboMa** [comment]
We cannot use `Broadcast.ArrayStyle`, if we want `LAStyle` to "win", i.e. `Array .+ LArray = LArray`. I will put a PR soon.

**Comment by MSeeker1340** [comment]
> We cannot use Broadcast.ArrayStyle, if we want LAStyle to "win", i.e. Array .+ LArray = LArray. I will put a PR soon.

Actually, what I found is that `Array .+ LArray == LArray` after changing it to `Broardcast.ArrayStyle`, but what's now broken is that `LArray{Int} .+ LArray{Float64} == Float64[]`. What's more curious is that `LArray{Int} .+ Float64[]` actually gives the correct `LArray{Float64}`.
