### ISSUE TITLE
Would there be a performance problem with large dimensions?

### ISSUE THREAD

**Issue by dmbates** [JuliaDiffEq/LabelledArrays.jl#38]
In the [`MixedModels` package](https://github.com/dmbates/MixedModels.jl) I currently return a [`NamedArray`](http://github.com/davidavdav/NamedArrays.jl) for means of random-effects.  These values are associated with the levels of a [`CategoricalArray`](http://github.com/JuliaData/CategoricalArrays.jl).
 
I had considered using a `LabelledArray` instead but held back because I thought they were implemented as `NamedTuple`s.  Looking at the code now I see that they are not. The values I want to label are always matrices with a small number of rows but occasionally a large number (thousands or tens of thousands) of columns.  Would that cause a performance problem?  I believe that long NamedTuples are problematic but it seems that LabelledArrays may by-pass those difficulties.

**Comment by ChrisRackauckas** [comment]
It wouldn't have runtime issues. The problem is that it stores the tuple of names in the type parameter in order to perform the index translations at compile-time. If you have tons of names, that compilation process may grow? I'm not sure exactly how that scales.
