### ISSUE TITLE
Why is LArray fixed to wrapping aan Array, instead of an AbstractArray?

### ISSUE THREAD

**Issue by rafaqz** [JuliaDiffEq/LabelledArrays.jl#47]
As I've been using a fork for the last months I hadn't realised this... I was hoping to swap out GPU arrays and views.

**Comment by ChrisRackauckas** [comment]
For larger arrays, wouldn't it have compilation issues to have so many names? But I guess views make sense.

**Comment by rafaqz** [comment]
Not so bad with slices, but I meant small GPU arrays that augment other larger arrays.

But labelled views are really useful with models that have repeating components.

**Comment by ChrisRackauckas** [comment]
I am not opposed to making it more generic if it's done right. It just needs to be inferrable. I think the swap @YingboMa did was because of inferrability issues, so some thought about performance is necessary here.

**Comment by rafaqz** [comment]
Ok, I assumed there was a problem like that.

The performance seems to still be good in the PR, and inference tests pass. Although I'm not confident I totally understand the issue or all the tests.
https://travis-ci.com/JuliaDiffEq/LabelledArrays.jl/jobs/179004631#L875
