### ISSUE TITLE
document accessing labels

### ISSUE THREAD

**Issue by bgctw** [JuliaDiffEq/LabelledArrays.jl#50]
I do not find documentation on accessing the lables of a LabelledArray. It would be nice to show this or hint to the documentation in the Readme.md

Currently I use for an LVector x: `typeof(x).parameters[4]`, but do not know if this is a save way. I would like to use a function `labels` or `names` that returns an array of NTuple(,Symbol) with an entry for each dimension.
Function `keys` already returns LinearIndices.

**Comment by ChrisRackauckas** [comment]
That's not a type-stable way to handle it IIRC. A `labels` function can be written that uses dispatch and grabs the type parameter though. That would be a quick fix.

**Comment by bgctw** [comment]
Thanks. I take away that there is currently no recommended way. It would be nice to access labels in a proper way at some time. I do not need a quick fix.

**Comment by ChrisRackauckas** [comment]
`symbols(::LArray{T,N,D<:AbstractArray{T,N},Syms}) = Syms`

Do that for each of the types. What I mean by it's a quick fix is that it can be easily added to the package if someone has time. You'd essentially make a PR that has 4 lines of that. I'll see if I remember to do so when I'm at a computer some time.
