### ISSUE TITLE
Allow subsetting with Vector of labels

### ISSUE THREAD

**Issue by bgctw** [JuliaDiffEq/LabelledArrays.jl#54]
Currently, only single entries can be accessed by labels.
Allow for extracting sub-arrays where the user specifies an entire vector of labels such as:

    zs = SLVector(a=1.0,b=2.0,c=3.0); 
    @test zs[[3,1]] == [3.,1.]
    @test zs[[:c,:a]] == [3.,1.]

**Comment by ChrisRackauckas** [comment]
#56
