### ISSUE TITLE
Retrieve a value using a tuple of symbols instead of just a symbol

### ISSUE THREAD

**Issue by rvignolo** [JuliaDiffEq/LabelledArrays.jl#76]
Is it possible to create a Static Labelled Array  that can retrieve values using something of the type:
```julia
m[:X1, :X2]
```
Suppose I need to define a matrix which specifies the correlations between objects:
```julia
Γ = SLArray{Tuple{2,2}}(X1X1=1, X2X1=2, X1X2=3, X2X2=4)
```
Then, we can get values using:
```julia
julia> Γ[:X1X2]
3
```
Is there a way we can retrieve a value using:
```julia
Γ[:X1, :X2]
```
instead?

I mean, is there a way that I can define the Static Labelled Array so I can retrieve values using something of the type `Γ[:X1, :X2]`?

Thanks!

**Comment by rvignolo** [comment]
Retrieving a value using the `dot` operator would be possible...?

**Comment by ChrisRackauckas** [comment]
You cannot concatenate symbols without allocating, i.e. `symbol("$(a[1])$(a[2]))`. This seems like a special case to leave to the user side, since otherwise you could have name clashes in general use. Indeed, if you're naming things X1 and X2, I'm not so sure what the utility of the names would be.

**Comment by rvignolo** [comment]
okay, perfect! Thanks!
